### ISSUE TITLE
Issue when precompiling in productin

### ISSUE THREAD

**Issue by MirkoCindric** [igorkasyanchuk/new_ckeditor#9]
```
()=>{this.backgroundColor=i.view.value});return i}_createDimensionFields(){const e=this.locale;const t=this.t;const n=new C_(e);n.text=t("cm");const i=new HI(e,WI);i.set({label:t("cj"),class:"ck-table-form__dimensions-row__width"});i.view.bind("value").to(this,"width");i.view.on("input",()=>{this.width=i.view.element.value});const o=new Yp(e);o.setTemplate({tag:"span",attributes:{class:["ck-table-form__dimension-operator"]},children:[{text:"×"}]});const r=new HI(e,WI);r.set({label:t("cn"),class:"ck-table-form__dimensions-row__height"});r.view.bind("value").to(this,"height");r.view.on("input",()=>{this.height=r.view.element.value});return{dimensionsLabel:n,widthInput:i,operatorLabel:o,heightInput:r}}_createAlignmentFields(){const e=this.locale;const t=this.t;const n=new C_(e);n.text=t("dj");const i=new Xb(e);i.set({isCompact:true,ariaLabel:t("dk")});sN({view:this,icons:CO,toolbar:i,labels:this._alignmentLabels,propertyName:"alignment",nameToValue:e=>e==="center"?"":e});return{alignmentLabel:n,alignmentToolbar:i}}_createActionButtons(){const e=this.locale;const t=this.t;const n=new fb(e);const i=new fb(e);const o=[this.borderWidthInput,this.borderColorInput,this.backgroundInput,this.widthInput,this.heightInput];n.set({label:t("cs"),icon:M_,class:"ck-button-save",type:"submit",withText:true});n.bind("isEnabled").toMany(o,"errorText",(...e)=>e.every(e=>!e));i.set({label:t("ct"),icon:I_,class:"ck-button-cancel",type:"cancel",withText:true});i.delegate("execute").to(this,"cancel");return{saveButtonView:n,cancelButtonView:i}}get _alignmentLabels(){const e=this.t;return{left:e("dl"),center:e("dm"),right:e("dn")}}}function TO(e){return!!e}var PO='<svg viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M8 2v5h4V2h1v5h5v1h-5v4h.021l-.172.351-1.916.28-.151.027c-.287.063-.54.182-.755.341L8 13v5H7v-5H2v-1h5V8H2V7h5V2h1zm4 6H8v4h4V8z" opacity=".6"/><path d="M15.5 11.5l1.323 2.68 2.957.43-2.14 2.085.505 2.946L15.5 18.25l-2.645 1.39.505-2.945-2.14-2.086 2.957-.43L15.5 11.5zM17 1a2 2 0 012 2v9.475l-.85-.124-.857-1.736a2.048 2.048 0 00-.292-.44L17 3H3v14h7.808l.402.392L10.935 19H3a2 2 0 01-2-2V3a2 2 0 012-2h14z"/></svg>';const SO=500;class EO extends pp{static get requires(){return[_b]}static get pluginName(){return"TablePropertiesUI"}constructor(e){super(e);e.config.define("table.tableProperties",{borderColors:aN,backgroundColors:aN})}init(){const e=this.editor;const t=e.t;this._balloon=e.plugins.get(_b);this.view=this._createPropertiesView();this._undoStepBatch=null;e.ui.componentFactory.add("tableProperties",e=>{const n=new fb(e);n.set({label:t("af"),icon:PO,tooltip:true});this.listenTo(n,"execute",()=>this._showView());return n})}destroy(){super.destroy();this.view.destroy()}_createPropertiesView(){const e=this.editor;const t=e.editing.view.document;const n=e.config.get("table.tableProperties");const i=xE(n.borderColors);const o=yE(e.locale,i);const r=xE(n.backgroundColors);const s=yE(e.locale,r);const a=new AO(e.locale,{borderColors:o,backgroundColors:s});const c=e.t;a.render();this.listenTo(a,"submit",()=>{this._hideView()});this.listenTo(a,"cancel",()=>{if(this._undoStepBatch.operations.length){e.execute("undo",this._undoStepBatch)}this._hideView()});a.keystrokes.set("Esc",(e,t)=>{this._hideView();t()});this.listenTo(e.ui,"update",()=>{if(!gT(t.selection)){this._hideView()}else if(this._isViewVisible){KI(e,"table")}});Fb({emitter:a,activator:()=>this._isViewInBalloon,contextElements:[this._balloon.view.element],callback:()=>this._hideView()});const l=eN(c);const d=tN(c);a.on("change:borderStyle",this._getPropertyChangeCallback("tableBorderStyle"));a.on("change:borderColor",this._getValidatedPropertyChangeCallback({viewField:a.borderColorInput,commandName:"tableBorderColor",errorText:l,validator:nN}));a.on("change:borderWidth",this._getValidatedPropertyChangeCallback({viewField:a.borderWidthInput,commandName:"tableBorderWidth",errorText:d,validator:oN}));a.on("change:backgroundColor",this._getValidatedPropertyChangeCallback({viewField:a.backgroundInput,commandName:"tableBackgroundColor",errorText:l,validator:nN}));a.on("change:width",this._getValidatedPropertyChangeCallback({viewField:a.widthInput,commandName:"tableWidth",errorText:d,validator:iN}));a.on("change:height",this._getValidatedPropertyChangeCallback({viewField:a.heightInput,commandName:"tableHeight",errorText:d,validator:iN}));a.on("change:alignment",this._getPropertyChangeCallback("tableAlignment"));return a}_fillViewFormFromCommandValues(){const e=this.editor.commands;this.view.set({borderStyle:e.get("tableBorderStyle").value||"",borderColor:e.get("tableBorderColor").value||"",borderWidth:e.get("tableBorderWidth").value||"",backgroundColor:e.get("tableBackgroundColor").value||"",width:e.get("tableWidth").value||"",height:e.get("tableHeight").value||"",alignment:e.get("tableAlignment").value||""})}_showView(){const e=this.editor;this._balloon.add({view:this.view,position:JI(e)});this._undoStepBatch=e.model.createBatch();this._fillViewFormFromCommandValues();this.view.focus()}_hideView(){if(!this._isViewInBalloon){return}const e=this.editor;this.stopListening(e.ui,"update");this.view.saveButtonView.focus();this._balloon.remove(this.view);this.editor.editing.view.focus()}get _isViewVisible(){return this._balloon.visibleView===this.view}get _isViewInBalloon(){return this._balloon.hasView(this.view)}_getPropertyChangeCallback(e){return(t,n,i)=>{this.editor.execute(e,{value:i,batch:this._undoStepBatch})}}_getValidatedPropertyChangeCallback({commandName:e,viewField:t,validator:n,errorText:i}){const o=hh(()=>{t.errorText=i},SO);return(i,r,s)=>{o.cancel();if(n(s)){this.editor.execute(e,{value:s,batch:this._undoStepBatch});t.errorText=null}else{o()}}}}class MO extends pp{static get pluginName(){return"TableProperties"}static get requires(){return[wO,EO]}}const IO="underline";class NO extends pp{static get pluginName(){return"UnderlineEditing"}init(){const e=this.editor;e.model.schema.extend("$text",{allowAttributes:IO});e.model.schema.setAttributeProperties(IO,{isFormatting:true,copyOnEnter:true});e.conversion.attributeToElement({model:IO,view:"u",upcastAlso:{styles:{"text-decoration":"underline"}}});e.commands.add(IO,new Qw(e,IO));e.keystrokes.set("CTRL+U","underline")}}var OO='<svg viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M3 18v-1.5h14V18zm2.2-8V3.6c0-.4.4-.6.8-.6.3 0 .7.2.7.6v6.2c0 2 1.3 2.8 3.2 2.8 1.9 0 3.4-.9 3.4-2.9V3.6c0-.3.4-.5.8-.5.3 0 .7.2.7.5V10c0 2.7-2.2 4-4.9 4-2.6 0-4.7-1.2-4.7-4z"/></svg>';const RO="underline";class VO extends pp{init(){const e=this.editor;const t=e.t;e.ui.componentFactory.add(RO,n=>{const i=e.commands.get(RO);const o=new fb(n);o.set({label:t("u"),icon:OO,keystroke:"CTRL+U",tooltip:true,isToggleable:true});o.bind("isOn","isEnabled").to(i,"value","isEnabled");this.listenTo(o,"execute",()=>{e.execute(RO);e.editing.view.focus()});return o})}}class DO extends pp{static get requires(){return[NO,VO]}static get pluginName(){return"Underline"}}class zO extends Gw{execute(){const e=this.editor.model;const t=e.document;e.change(n=>{LO(this.editor.model,n,t.selection,e.schema);this.fire("afterExecute",{writer:n})})}}function LO(e,t,n,i){const o=n.isCollapsed;const r=n.getFirstRange();const s=r.start.parent;const a=r.end.parent;if(i.isLimit(s)||i.isLimit(a)){if(!o&&s==a){e.deleteContent(n)}return}if(o){const e=eS(t.model.schema,n.getAttributes());BO(t,r.start);t.setSelectionAttribute(e)}else{const i=!(r.start.isAtStart&&r.end.isAtEnd);const o=s==a;e.deleteContent(n,{leaveUnmerged:i});if(i){if(o){BO(t,n.focus)}else{t.setSelection(a,0)}}}}function BO(e,t){e.split(t);e.setSelection(t.parent.nextSibling,0)}class jO extends pp{static get pluginName(){return"Enter"}init(){const e=this.editor;const t=e.editing.view;const n=t.document;t.addObserver(sS);e.commands.add("enter",new zO(e));this.listenTo(n,"enter",(n,i)=>{i.preventDefault();if(i.isSoft){return}e.execute("enter");t.scrollToTheSelection()},{priority:"low"})}}class FO extends pp{static get requires(){return[ay,jO,aS,CI,fA]}static get pluginName(){return"Essentials"}}n.d(t,"default",(function(){return HO}));class HO extends Bw{}HO.builtinPlugins=[qw,tk,ak,bk,Ik,j_,Z_,mv,_v,gy,_y,Gx,MC,yA,eT,EP,MP,$P,XP,RS,cE,kE,SE,OE,WE,eM,wM,KM,JM,iI,oI,RI,jI,cO,MO,DO,FO,_k]}])["default"]}));
 7 //# sourceMappingURL=ckeditor.js.map
 8 ;
==
/Users/mirko/.gem/ruby/2.6.3/gems/uglifier-4.2.0/lib/uglifier.rb:291:in `parse_result'
/Users/mirko/.gem/ruby/2.6.3/gems/uglifier-4.2.0/lib/uglifier.rb:221:in `run_uglifyjs'
/Users/mirko/.gem/ruby/2.6.3/gems/uglifier-4.2.0/lib/uglifier.rb:166:in `compile'
/Users/mirko/.gem/ruby/2.6.3/gems/sprockets-3.7.2/lib/sprockets/uglifier_compressor.rb:53:in `call'
/Users/mirko/.gem/ruby/2.6.3/gems/sprockets-3.7.2/lib/sprockets/uglifier_compressor.rb:28:in `call'
/Users/mirko/.gem/ruby/2.6.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Users/mirko/.gem/ruby/2.6.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/Users/mirko/.gem/ruby/2.6.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/Users/mirko/.gem/ruby/2.6.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/Users/mirko/.gem/ruby/2.6.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/Users/mirko/.gem/ruby/2.6.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/Users/mirko/.gem/ruby/2.6.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_c
```

Getting this error when running assets:precompile but works fine in dev

**Comment by igorkasyanchuk** [comment]
Hi, I can only suggest try fix error by your own somehow.
Also I think this is because of something is wrong with uglifier, so perphaps try this
https://stackoverflow.com/questions/76271387/rails-gem-uglifier-4-2-does-not-support-async-await-how-to-fix
https://github.com/ahorek/terser-ruby
